---
rdoc_url: https://bogomips.org/ruby_posix_mq/
cgit_url: https://bogomips.org/ruby_posix_mq.git
git_url: git://bogomips.org/ruby_posix_mq.git
public_email: ruby-posix-mq@bogomips.org
ml_url: https://bogomips.org/ruby-posix-mq/
changelog_since: 0.4.0
merge_html:
  posix-mq-rb_1: Documentation/posix-mq-rb.1.html
